/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiAdminCleanupRouteImport } from './routes/api.admin-cleanup'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'
import { Route as RoomSlugIndexRouteImport } from './routes/room.$slug.index'
import { Route as RoomSlugCassetteRouteImport } from './routes/room.$slug.cassette'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminCleanupRoute = ApiAdminCleanupRouteImport.update({
  id: '/api/admin-cleanup',
  path: '/api/admin-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugIndexRoute = RoomSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomSlugRoute,
} as any)
const RoomSlugCassetteRoute = RoomSlugCassetteRouteImport.update({
  id: '/cassette',
  path: '/cassette',
  getParentRoute: () => RoomSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generate': typeof GenerateRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-cleanup': typeof ApiAdminCleanupRoute
  '/room/$slug': typeof RoomSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/room/$slug/cassette': typeof RoomSlugCassetteRoute
  '/room/$slug/': typeof RoomSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-cleanup': typeof ApiAdminCleanupRoute
  '/admin': typeof AdminIndexRoute
  '/room/$slug/cassette': typeof RoomSlugCassetteRoute
  '/room/$slug': typeof RoomSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generate': typeof GenerateRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-cleanup': typeof ApiAdminCleanupRoute
  '/room/$slug': typeof RoomSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/room/$slug/cassette': typeof RoomSlugCassetteRoute
  '/room/$slug/': typeof RoomSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/generate'
    | '/admin/login'
    | '/api/admin-cleanup'
    | '/room/$slug'
    | '/admin/'
    | '/room/$slug/cassette'
    | '/room/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate'
    | '/admin/login'
    | '/api/admin-cleanup'
    | '/admin'
    | '/room/$slug/cassette'
    | '/room/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/generate'
    | '/admin/login'
    | '/api/admin-cleanup'
    | '/room/$slug'
    | '/admin/'
    | '/room/$slug/cassette'
    | '/room/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GenerateRoute: typeof GenerateRoute
  ApiAdminCleanupRoute: typeof ApiAdminCleanupRoute
  RoomSlugRoute: typeof RoomSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin-cleanup': {
      id: '/api/admin-cleanup'
      path: '/api/admin-cleanup'
      fullPath: '/api/admin-cleanup'
      preLoaderRoute: typeof ApiAdminCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug/': {
      id: '/room/$slug/'
      path: '/'
      fullPath: '/room/$slug/'
      preLoaderRoute: typeof RoomSlugIndexRouteImport
      parentRoute: typeof RoomSlugRoute
    }
    '/room/$slug/cassette': {
      id: '/room/$slug/cassette'
      path: '/cassette'
      fullPath: '/room/$slug/cassette'
      preLoaderRoute: typeof RoomSlugCassetteRouteImport
      parentRoute: typeof RoomSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RoomSlugRouteChildren {
  RoomSlugCassetteRoute: typeof RoomSlugCassetteRoute
  RoomSlugIndexRoute: typeof RoomSlugIndexRoute
}

const RoomSlugRouteChildren: RoomSlugRouteChildren = {
  RoomSlugCassetteRoute: RoomSlugCassetteRoute,
  RoomSlugIndexRoute: RoomSlugIndexRoute,
}

const RoomSlugRouteWithChildren = RoomSlugRoute._addFileChildren(
  RoomSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GenerateRoute: GenerateRoute,
  ApiAdminCleanupRoute: ApiAdminCleanupRoute,
  RoomSlugRoute: RoomSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
