insert into public.oneliners (scene_id, text_en, text_hi, daypart_tag, weight)
select s.id, v.en, v.hi, v.dp, 1 from public.scenes s
join (values
 ('sainik-dhaba','Tandoor se seedhi roti — thoda jal gayi, swaad wahi.','तंदूर से सीधी रोटी — थोड़ी जल गई, स्वाद वही।','all'),
 ('sainik-dhaba','Trucker bhai ne cassette palat di.','ट्रकर भाई ने कैसेट पलट दी।','all'),
 ('sainik-dhaba','Dal makhani ki khushbu highway tak jaa rahi hai.','दाल मखनी की खुशबू हाइवे तक जा रही है।','night'),
 ('nai-ki-dukaan','Bas thoda aur chhota kar do, bhaiya.','बस थोड़ा और छोटा कर दो, भइया।','all'),
 ('nai-ki-dukaan','Aaine mein do log — ek aap, ek 1994.','आईने में दो लोग — एक आप, एक 1994।','all'),
 ('nai-ki-dukaan','Champi karwa lijiye, sar halka ho jayega.','चंपी करवा लीजिए, सर हल्का हो जाएगा।','evening'),
 ('chai-ki-tapri','Kadak, kam cheeni — hamesha ki tarah.','कड़क, कम चीनी — हमेशा की तरह।','all'),
 ('chai-ki-tapri','Kulhad garam hai, phook maar ke piyo.','कुल्हड़ गरम है, फूँक मार के पियो।','morning'),
 ('chai-ki-tapri','Ek cutting, do log, teen ghante.','एक कटिंग, दो लोग, तीन घंटे।','evening'),
 ('raj-mistri','Plumb line seedhi, dil bhi seedha.','प्लंब लाइन सीधी, दिल भी सीधा।','all'),
 ('raj-mistri','Do bori seement aur aa jaaye.','दो बोरी सीमेंट और आ जाए।','day'),
 ('raj-mistri','Chhat dhalne wali hai — radio tez kar do.','छत ढलने वाली है — रेडियो तेज़ कर दो।','day'),
 ('raj-mistri','Chuna, reti, aur ek adhoori deewar.','चूना, रेती, और एक अधूरी दीवार।','evening'),
 ('raat-ki-bus','Khidki thodi khuli hai, hawa lag rahi hai.','खिड़की थोड़ी खुली है, हवा लग रही है।','night'),
 ('raat-ki-bus','Driver bhai ne dhaba pe das minute bola tha.','ड्राइवर भाई ने ढाबे पे दस मिनट बोला था।','night'),
 ('raat-ki-bus','Peeche wali seat pe koi so gaya hai.','पीछे वाली सीट पे कोई सो गया है।','night'),
 ('sarkari-daftar','File neeche wale kaunter pe hai, sir.','फ़ाइल नीचे वाले काउंटर पे है, सर।','day'),
 ('sarkari-daftar','Sahab lunch pe gaye hain, do baje aayenge.','साहब लंच पे गए हैं, दो बजे आएँगे।','day'),
 ('sarkari-daftar','Ek muhar, teen signature, chhah chakkar.','एक मुहर, तीन सिग्नेचर, छह चक्कर।','all'),
 ('doordarshan-shaam','Rukavat ke liye khed hai.','रुकावट के लिए खेद है।','evening'),
 ('doordarshan-shaam','Antenna thoda ghuma do, picture saaf ho jayegi.','एंटीना थोड़ा घुमा दो, पिक्चर साफ़ हो जाएगी।','evening'),
 ('doordarshan-shaam','Chitrahaar shuru hone wala hai.','चित्रहार शुरू होने वाला है।','evening'),
 ('doordarshan-shaam','Ma ne bola tha — khaana TV ke saamne nahi.','माँ ने बोला था — खाना टीवी के सामने नहीं।','night'),
 ('rail-yatra','Gaadi do number platform pe aa rahi hai.','गाड़ी दो नंबर प्लेटफ़ॉर्म पे आ रही है।','all'),
 ('rail-yatra','Darwaaze pe khade mat raho.','दरवाज़े पे खड़े मत रहो।','all'),
 ('bhojpuriya-devara','Naach shuru, dhol baje ta.','नाच शुरू, ढोल बजे ता।','evening'),
 ('bhojpuriya-devara','Gaon ke mele mein bhid ba.','गाँव के मेले में भीड़ बा।','evening'),
 ('bhojpuriya-devara','Balam ji, thoda dhire.','बलम जी, थोड़ा धीरे।','all'),
 ('corporate-majdoor','Ek aur meeting, jo mail bhi ho sakti thi.','एक और मीटिंग, जो मेल भी हो सकती थी।','day'),
 ('corporate-majdoor','AC 18 pe hai aur sweater laana bhool gaye.','एसी 18 पे है और स्वेटर लाना भूल गए।','day'),
 ('corporate-majdoor','Cab 9 baje, kaam 11 tak.','कैब 9 बजे, काम 11 तक।','night'),
 ('corporate-majdoor','Chai break hi asli appraisal hai.','चाय ब्रेक ही असली अप्रेज़ल है।','evening')
) as v(slug, en, hi, dp) on v.slug = s.slug;